### ISSUE TITLE
Non-graceful failure when PowerDNS API stats are different

### ISSUE THREAD

**Issue by eburcat** [jimmystewpot/pdns-statsd-proxy#3]
On our PowerDNS the statistics from the API are a slightly different - and as a results only 2 of the statistics are actually sent.
Probably when there's a missing statistic in the json result - the loop stops.
We've patched by setting in stats.go exactly the statistics that our server is providing - but there should be a better handling of this issue.

**Comment by jimmystewpot** [comment]
What version of the powerdns software are you using?

**Comment by jimmystewpot** [comment]
Should we consider this to be closed?
